from .mazes import Maze
from .wires import Wires
from .memory import Memory
from .keypads import Keypad
from .simon_says import Simon
from .the_button import Button
from .passwords import Password
from .morse_code import MorseCode
from .whos_on_first import WhosOnFirst
from .wire_sequences import WireSequence
from .complicated_wires import ComplicatedWires
